name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Buildozer and Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libqt4-dev libgtk2.0-dev curl
        python3 -m pip install --user --upgrade buildozer

    - name: Build and Sign APK
      run: |
        buildozer init
        buildozer android clean
        buildozer android release
      env:
        P4A_RELEASE_KEYSTORE_PASSWD: ${{ secrets.RELEASE_KEYSTORE_PASSWD }}
        P4A_RELEASE_KEYALIAS_NAME: ${{ secrets.RELEASE_KEYALIAS_NAME }}
        P4A_RELEASE_KEYALIAS_PASSWD: ${{ secrets.RELEASE_KEYALIAS_PASSWD }}

    - name: Upload APK file
      uses: actions/upload-artifact@v2
      with:
        name: kivymdapp
        path: ./bin/*.apk
